// Locates the header row within the first few rows of a worksheet by
// matching its first cell against the expected header text, rather than
// assuming it's always row 1 — a template generated by buildStyledSheet()
// with a `legend` has the real header on row 3 (legend, blank, header),
// while a plain export has it on row 1. This lets every importer accept
// both "downloaded the template, filled it in" and "re-uploading our own
// export" without caring which shape it got.
function findHeaderRowIndex(ws, expectedFirstCell, maxScan = 5) {
  const target = expectedFirstCell.trim().toUpperCase();
  for (let r = 1; r <= Math.min(maxScan, ws.rowCount); r++) {
    const first = ws.getRow(r).values[1];
    if (first !== undefined && first !== null && String(first).trim().toUpperCase() === target) return r;
  }
  return null;
}

module.exports = { findHeaderRowIndex };
