// Locates the header row within the first few rows of a worksheet by
// matching its first cell against the expected header text, rather than
// assuming it's always row 1 — a template generated by buildStyledSheet()
// with a `legend` has the real header on row 3 (legend, blank, header),
// while a plain export has it on row 1. This lets every importer accept
// both "downloaded the template, filled it in" and "re-uploading our own
// export" without caring which shape it got.
function findHeaderRowIndex(ws, expectedFirstCell, maxScan = 5) {
  const target = expectedFirstCell.trim().toUpperCase();
  for (let r = 1; r <= Math.min(maxScan, ws.rowCount); r++) {
    const first = ws.getRow(r).values[1];
    if (first !== undefined && first !== null && String(first).trim().toUpperCase() === target) return r;
  }
  return null;
}

// Reads a "time" cell as a plain "HH:MM" string, however Excel happens to
// have stored it. A cell someone TYPED directly into Excel (rather than
// generated by our own template) is very often auto-detected as a time
// value, not left as text — ExcelJS then hands it back as a JS Date
// anchored to the Excel date epoch (1899-12-30) with only the time-of-day
// meaningful, not a plain string. Blindly String()-ing that produces an
// ISO timestamp that fails any "HH:MM" check outright, which is exactly
// the false "wrong format" error a real user hits typing a time in
// naturally. Returns "" for a blank cell.
function parseExcelTimeCell(value) {
  if (value === undefined || value === null || value === "") return "";
  if (value instanceof Date) {
    const h = String(value.getUTCHours()).padStart(2, "0");
    const m = String(value.getUTCMinutes()).padStart(2, "0");
    return `${h}:${m}`;
  }
  return String(value).trim();
}

module.exports = { findHeaderRowIndex, parseExcelTimeCell };
