// TASK ALLOCATION MODULE — Task Generator orchestration (Section 7).
// Converts flight instances into MaintenanceTask rows using the station's
// configured AllocationRule set — all the actual conversion math lives in
// taskAllocationEngine.generateTasksFromFlightInstance (pure, tested); this
// file only fetches inputs, de-duplicates against what's already generated,
// and persists.
const taskAllocationConfigRepo = require("../repositories/taskAllocationConfigRepository");
const maintenanceTaskRepo = require("../repositories/maintenanceTaskRepository");
const { generateTasksFromFlightInstance } = require("../utils/taskAllocationEngine");
const ApiError = require("../utils/ApiError");

function dateOnly(d) {
  const x = new Date(d);
  x.setUTCHours(0, 0, 0, 0);
  return x;
}
function dateKey(d) {
  const x = new Date(d);
  return `${x.getUTCFullYear()}${String(x.getUTCMonth() + 1).padStart(2, "0")}${String(x.getUTCDate()).padStart(2, "0")}`;
}

// Generates tasks for every flight instance on `date` against every
// enabled AllocationRule for the station. Idempotent per (flightInstanceId,
// ruleId, anchor event) — re-running for the same day never creates a
// duplicate task, it just reports 0 new for anything already generated, so
// a dispatcher can safely re-run this after importing a correction.
async function generateTasksForDate(stationId, date, actorId) {
  const from = dateOnly(date);
  const to = new Date(from.getTime() + 24 * 60 * 60 * 1000 - 1);

  const [flightInstances, rules, existingTasks] = await Promise.all([
    taskAllocationConfigRepo.listFlightInstances(stationId, from, to),
    taskAllocationConfigRepo.listRules(stationId),
    maintenanceTaskRepo.listTasks(stationId, { dateFrom: from, dateTo: to }),
  ]);

  // A task already generated from this exact (flightInstance, rule, planned
  // start) combination is skipped — the planned start distinguishes an
  // ARRIVAL-anchored and a DEPARTURE-anchored task a "BOTH" rule produces
  // for the same flight instance + rule pair.
  const existingKeys = new Set(existingTasks
    .filter(t => t.source === "AUTO_GENERATED")
    .map(t => `${t.flightInstanceId}|${t.ruleId}|${new Date(t.plannedStart).getTime()}`));

  const drafts = [];
  for (const fi of flightInstances) {
    for (const draft of generateTasksFromFlightInstance(fi, rules)) {
      const key = `${draft.flightInstanceId}|${draft.ruleId}|${draft.plannedStart.getTime()}`;
      if (existingKeys.has(key)) continue;
      drafts.push({ ...draft, stationId });
    }
  }
  if (!drafts.length) return { generated: 0, skipped: flightInstances.length ? existingKeys.size : 0, tasks: [] };

  let seq = existingTasks.filter(t => dateKey(t.plannedStart) === dateKey(date)).length;
  const created = [];
  for (const draft of drafts) {
    seq += 1;
    const taskNumber = `T-${dateKey(draft.plannedStart)}-${String(seq).padStart(3, "0")}`;
    const task = await maintenanceTaskRepo.createTask({
      ...draft, taskNumber, createdById: actorId, updatedById: actorId,
    });
    await maintenanceTaskRepo.recordStatusChange(task.id, null, "UNASSIGNED", actorId, "Generated by Task Generator");
    created.push(task);
  }
  return { generated: created.length, tasks: created };
}

async function assertRuleBelongsToStation(ruleId, stationId) {
  const rule = await taskAllocationConfigRepo.findRuleById(ruleId);
  if (!rule || rule.stationId !== stationId) throw ApiError.notFound("Allocation rule not found");
  return rule;
}

module.exports = { generateTasksForDate, assertRuleBelongsToStation };
